orchard.web.1.3.10-git/Modules/Orchard.Packaging/Controllers/PackagingServicesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using NuGet;
using Orchard.Environment.Configuration;
using Orchard.Environment.Extensions.Models;
using Orchard.FileSystems.AppData;
using Orchard.Localization;
using Orchard.Modules.Services;
using Orchard.Mvc.Extensions;
using Orchard.Packaging.Services;
using Orchard.Packaging.ViewModels;
using Orchard.Recipes.Models;
using Orchard.Recipes.Services;
using Orchard.Security;
using Orchard.Themes;
using Orchard.UI.Admin;
using Orchard.UI.Notify;
using Orchard.Utility.Extensions;
using IPackageManager = Orchard.Packaging.Services.IPackageManager;
using PackageBuilder = Orchard.Packaging.Services.PackageBuilder;

namespace Orchard.Packaging.Controllers {
    [Themed, Admin]
    public class PackagingServicesController : Controller {

        private readonly ShellSettings _shellSettings;
        private readonly IPackageManager _packageManager;
        private readonly IPackagingSourceManager _packagingSourceManager;
        private readonly IAppDataFolderRoot _appDataFolderRoot;
        private readonly INotifier _notifier;
        private readonly IModuleService _moduleService;
        private readonly IRecipeHarvester _recipeHarvester;
        private readonly IRecipeManager _recipeManager;

        public PackagingServicesController(
            ShellSettings shellSettings,
            IPackageManager packageManager,
            IPackagingSourceManager packagingSourceManager,
            INotifier notifier,
            IAppDataFolderRoot appDataFolderRoot,
            IOrchardServices services,
            IModuleService moduleService)
            : this(shellSettings, packageManager, packagingSourceManager, notifier, appDataFolderRoot, services, moduleService, null, null) {
        }

        public PackagingServicesController(
            ShellSettings shellSettings,
            IPackageManager packageManager,
            IPackagingSourceManager packagingSourceManager,
            INotifier notifier,
            IAppDataFolderRoot appDataFolderRoot,
            IOrchardServices services,
            IModuleService moduleService,
            IRecipeHarvester recipeHarvester,
            IRecipeManager recipeManager) {

            _shellSettings = shellSettings;
            _packageManager = packageManager;
            _notifier = notifier;
            _appDataFolderRoot = appDataFolderRoot;
            _moduleService = moduleService;
            _recipeHarvester = recipeHarvester;
            _recipeManager = recipeManager;
            _packagingSourceManager = packagingSourceManager;
            Services = services;

            T = NullLocalizer.Instance;
            Logger = Logging.NullLogger.Instance;
        }

        public Localizer T { get; set; }
        public IOrchardServices Services { get; set; }
        public Logging.ILogger Logger { get; set; }

        public ActionResult AddTheme(string returnUrl) {
            if (_shellSettings.Name != ShellSettings.DefaultName || !Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to add themes")))
                return new HttpUnauthorizedResult();

            return View();
        }

        [HttpPost, ActionName("RemoveTheme")]
        public ActionResult RemoveThemePOST(string themeId, string returnUrl, string retryUrl) {
            if (_shellSettings.Name != ShellSettings.DefaultName || !Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to remove themes")))
                return new HttpUnauthorizedResult();

            return UninstallPackage(PackageBuilder.BuildPackageId(themeId, DefaultExtensionTypes.Theme), returnUrl, retryUrl);
        }

        public ActionResult AddModule(string returnUrl) {
            if (_shellSettings.Name != ShellSettings.DefaultName || !Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to add modules")))
                return new HttpUnauthorizedResult();

            return View();
        }

        public ActionResult InstallGallery(string packageId, string version, int sourceId, string redirectUrl) {
            if (_shellSettings.Name != ShellSettings.DefaultName || !Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to add sources")))
                return new HttpUnauthorizedResult();

            try {
                var source = _packagingSourceManager.GetSources().Where(s => s.Id == sourceId).FirstOrDefault();
                if (source == null) {
                    return HttpNotFound();
                }

                PackageInfo packageInfo = _packageManager.Install(packageId, version, source.FeedUrl, HostingEnvironment.MapPath("~/"));

                if (DefaultExtensionTypes.IsTheme(packageInfo.ExtensionType)) {
                    Services.Notifier.Information(T("The theme has been successfully installed. It can be enabled in the \"Themes\" page accessible from the menu."));
                } else if (DefaultExtensionTypes.IsModule(packageInfo.ExtensionType)) {
                    Services.Notifier.Information(T("The module has been successfully installed."));

                    IPackageRepository packageRepository = PackageRepositoryFactory.Default.CreateRepository(new PackageSource(source.FeedUrl, "Default"));
                    IPackage package = packageRepository.FindPackage(packageId);
                    ExtensionDescriptor extensionDescriptor = _packageManager.GetExtensionDescriptor(package, packageInfo.ExtensionType);

                    return InstallPackageDetails(extensionDescriptor, redirectUrl);
                }
            }
            catch (Exception exception) {
                this.Error(exception, T("Package installation failed."), Logger, Services.Notifier);
            }

            return Redirect(redirectUrl);
        }

        public ActionResult InstallLocally(string redirectUrl) {
            if (_shellSettings.Name != ShellSettings.DefaultName || !Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to install packages")))
                return new HttpUnauthorizedResult();

            try {
                if (Request.Files == null ||
                    Request.Files.Count == 0 ||
                    string.IsNullOrWhiteSpace(Request.Files.Get(0).FileName)) {

                    throw new OrchardException(T("Select a file to upload."));
                }

                HttpPostedFileBase file = Request.Files.Get(0);
                string fullFileName = Path.Combine(_appDataFolderRoot.RootFolder, Path.GetFileName(file.FileName)).Replace(Path.DirectorySeparatorChar, '/');
                file.SaveAs(fullFileName);
                ZipPackage package = new ZipPackage(fullFileName);
                PackageInfo packageInfo = _packageManager.Install(package, _appDataFolderRoot.RootFolder, HostingEnvironment.MapPath("~/"));
                ExtensionDescriptor extensionDescriptor = _packageManager.GetExtensionDescriptor(package, packageInfo.ExtensionType);
                System.IO.File.Delete(fullFileName);

                if (DefaultExtensionTypes.IsTheme(extensionDescriptor.ExtensionType)) {
                    Services.Notifier.Information(T("The theme has been successfully installed. It can be enabled in the \"Themes\" page accessible from the menu."));
                } else if (DefaultExtensionTypes.IsModule(extensionDescriptor.ExtensionType)) {
                    Services.Notifier.Information(T("The module has been successfully installed."));

                    return InstallPackageDetails(extensionDescriptor, redirectUrl);
                }
            }
            catch (Exception exception) {
                this.Error(exception, T("Package uploading and installation failed."), Logger, Services.Notifier);
            }

            return Redirect(redirectUrl);
        }

        private ActionResult InstallPackageDetails(ExtensionDescriptor extensionDescriptor, string redirectUrl) {
            if (DefaultExtensionTypes.IsModule(extensionDescriptor.ExtensionType)) {
                List<PackagingInstallFeatureViewModel> features = extensionDescriptor.Features
                    .Where(featureDescriptor => !DefaultExtensionTypes.IsTheme(featureDescriptor.Extension.ExtensionType))
                    .Select(featureDescriptor => new PackagingInstallFeatureViewModel {
                        Enable = true, // by default all features are enabled
                        FeatureDescriptor = featureDescriptor
                    }).ToList();

                List<PackagingInstallRecipeViewModel> recipes = null;
                if (_recipeHarvester != null) {
                    recipes = _recipeHarvester.HarvestRecipes(extensionDescriptor.Id)
                        .Select(recipe => new PackagingInstallRecipeViewModel {
                            Execute = false, // by default no recipes are executed
                            Recipe = recipe
                        }).ToList();
                }

                if (features.Count > 0) {
                    return View("InstallModuleDetails", new PackagingInstallViewModel {
                        Features = features,
                        Recipes = recipes,
                        ExtensionDescriptor = extensionDescriptor
                    });
                }
            }

            return Redirect(redirectUrl);
        }

        [HttpPost, ActionName("InstallPackageDetails")]
        public ActionResult InstallPackageDetailsPOST(PackagingInstallViewModel packagingInstallViewModel, string redirectUrl) {
            if (_shellSettings.Name != ShellSettings.DefaultName || !Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to add sources")))
                return new HttpUnauthorizedResult();

            try {

orchard.web.1.3.10-git/Modules/Orchard.Packaging/Views/Gallery/AddSource.cshtml
@model Orchard.Packaging.ViewModels.PackagingAddSourceViewModel

@{ Layout.Title = T("Add a Feed").ToString(); }

@using ( Html.BeginFormAntiForgeryPost(Url.Action("AddSource")) ) {
    @Html.ValidationSummary()
    <fieldset>
        <label for="Url">@T("Feed Url")</label>
        <input id="Url" class="textMedium" name="Url" type="text" value="@Model.Url"/>
    </fieldset>
    <fieldset>
        <button class="primaryAction" type="submit">@T("Add Feed")</button>
    </fieldset>
 }

orchard.web.1.3.10-git/Modules/Orchard.Packaging/Views/Gallery/Modules.cshtml
@model Orchard.Packaging.ViewModels.PackagingExtensionsViewModel
@using Orchard.Packaging.ViewModels;
@using System.Linq;

@{
    Style.Require("PackagingAdmin");

    Layout.Title = T("Modules").ToString();
}

@using (Html.BeginFormAntiForgeryPost(Url.Action("Modules", "Gallery"))) {
    <fieldset class="bulk-actions bulk-actions-auto">
        <label for="sourceId">@T("Feed:")</label>
        <select id="sourceId" name="@Html.NameOf(m => m.Options.SourceId)">
            @Html.SelectOption(Model.Options.SourceId, null, T("All feeds").ToString())
            @foreach (var source in Model.Sources) {
                @Html.SelectOption(Model.Options.SourceId, source.Id, source.FeedTitle)
            }
        </select>
    </fieldset>

    <fieldset class="bulk-actions bulk-actions-auto">
        <label for="filterResults">@T("Sort by:")</label>
        <select id="filterResults" name="@Html.NameOf(m => m.Options.Order)">
            @Html.SelectOption(Model.Options.Order, PackagingExtensionsOrder.Downloads, T("Downloads").ToString())
            @Html.SelectOption(Model.Options.Order, PackagingExtensionsOrder.Ratings, T("Ratings").ToString())
            @Html.SelectOption(Model.Options.Order, PackagingExtensionsOrder.Alphanumeric, T("Alphanumeric").ToString())
        </select>

        <button id="apply-bulk-actions" class="apply-bulk-actions-auto" type="submit">@T("Apply")</button>
    </fieldset>

    <fieldset class="search-actions">
        <input type="text" id="searchText" class="text-box single-line" name="@Html.NameOf(m => m.Options.SearchText)" value="@Model.Options.SearchText" />

        <button type="submit">@T("Search")</button>
    </fieldset>

    if (Model.Extensions.Count() > 0) {
        <ul class="contentItems">
        @foreach (var item in Model.Extensions) {
            <li>
                @{
            string iconUrl = @item.IconUrl;
            if (string.IsNullOrWhiteSpace(iconUrl)) {
                iconUrl = Href("../../Content/Images/ModuleDefaultIcon.png");
            }
                }

                <div class="summary">
                 @if (item.Notifications != null && item.Notifications.Count > 0) {
                                <div class="notifications">
                                @foreach (string notification in item.Notifications) {
                                    <h5>@Html.Raw(notification)</h5>
                                }
                                </div>
                            }
                </div>
                <div class="iconThumbnail">
                    <div class="extensionDetails column">
                        <div class="extensionName @if (item.Installed) {<text>installed</text>}">
                            @if (!string.IsNullOrWhiteSpace(item.GalleryDetailsUrl)) {
                                <a href="@item.GalleryDetailsUrl">
                                    <h2>@item.Title<span> - @T("Version: {0}", item.Version)</span></h2>
                                </a>
                            } else {
                                <h2>@item.Title<span> - @T("Version: {0}", item.Version)</span></h2>
                            }
                        </div>


                        <div class="related">
                            @Html.ActionLink(T("Install").ToString(), "InstallGallery", "PackagingServices", new RouteValueDictionary { { "packageId", item.PackageId }, { "version", item.Version }, { "sourceId", item.Source.Id }, { "redirectUrl", HttpContext.Current.Request.RawUrl } }, null)@T(" | ")
                            <a href="@item.PackageStreamUri">@T("Download")</a>
                        </div>

                        <div class="properties">
                            <p>@(item.Description == null ? T("(No description").Text : item.Description)</p>
                            <ul class="pageStatus group">
                                <li>@T("Last Updated: {0}", item.LastUpdated)</li>
                                <li>&nbsp;&#124;&nbsp;@T("Author: {0}", !string.IsNullOrEmpty(item.Authors) ? item.Authors : T("Unknown").ToString())</li>
                                <li>&nbsp;&#124;&nbsp;@T("Downloads: {0}", item.DownloadCount)</li>
                                <li>&nbsp;&#124;&nbsp;@T("Website: ")
                                    @if (!string.IsNullOrEmpty(item.ProjectUrl)) { <a href="@item.ProjectUrl">@item.ProjectUrl</a> } else { @T("Unknown").ToString() }
                                </li>
                                <li class="rating">&nbsp;&#124;&nbsp;@T("Rating: ")
                                        <div class="ratings" style="width:@(15 * 5)px" title="@T("Rating: {0} out of 5 ({1} total).", item.Rating, item.RatingsCount)">
                                            <div class="score" style="width:@(15 * (item.Rating))px">&nbsp;</div>
                                        </div>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class="extensionThumbnail column">
                        <img src="@iconUrl" class="thumbnail" alt="module" />
                    </div>
                </div>
            </li>}
        </ul>
    }

    @Display(Model.Pager)
}

orchard.web.1.3.10-git/Modules/Orchard.Packaging/Views/Gallery/Sources.cshtml
@model Orchard.Packaging.ViewModels.PackagingSourcesViewModel

@{ Layout.Title = T("Settings").ToString(); }

<h2>@T("Gallery")</h2>
<div class="manage">
    @Html.ActionLink(T("Add Feed").Text, "AddSource", new { }, new { @class = "button primaryAction" })
</div>

<fieldset>
    <table class="items" summary="@T("This is a table of the gallery feeds in your application")">
        <colgroup>
            <col id="Col1" />
            <col id="Col2" />
            <col id="Col3" />
        </colgroup>
        <thead>
            <tr>
                <th scope="col">@T("Title")</th>
                <th scope="col">@T("Url")</th>
                <th scope="col"></th>
            </tr>
        </thead>
        @foreach ( var item in Model.Sources ) {
        <tr>
            <td>@item.FeedTitle</td>
            <td>@Html.Link(item.FeedUrl, item.FeedUrl)</td>
            <td>@Html.ActionLink(T("Delete").ToString(), "Remove", new { id = item.Id })</td>
        </tr>
        }
    </table>
</fieldset>

orchard.web.1.3.10-git/Modules/Orchard.Packaging/Views/Gallery/Themes.cshtml
@model Orchard.Packaging.ViewModels.PackagingExtensionsViewModel
@using Orchard.Packaging.ViewModels;
@using System.Linq;

@{
    Style.Require("PackagingAdmin");

    Layout.Title = T("Themes").ToString();
}

@using (Html.BeginFormAntiForgeryPost(Url.Action("Themes", "Gallery"))) {
    <fieldset class="bulk-actions bulk-actions-auto">
        <label for="sourceId">@T("Show")</label>
        <select id="sourceId" name="@Html.NameOf(m => m.Options.SourceId)">
            @Html.SelectOption(Model.Options.SourceId, null, T("All feeds").ToString())
            @foreach (var source in Model.Sources) {
                @Html.SelectOption(Model.Options.SourceId, source.Id, source.FeedTitle)
            }
        </select>
    </fieldset>

    <fieldset class="bulk-actions bulk-actions-auto">
        <label for="filterResults">@T("Sort by:")</label>
        <select id="filterResults" name="@Html.NameOf(m => m.Options.Order)">
            @Html.SelectOption(Model.Options.Order, PackagingExtensionsOrder.Downloads, T("Downloads").ToString())
            @Html.SelectOption(Model.Options.Order, PackagingExtensionsOrder.Ratings, T("Ratings").ToString())
            @Html.SelectOption(Model.Options.Order, PackagingExtensionsOrder.Alphanumeric, T("Alphanumeric").ToString())
        </select>

        <button id="apply-bulk-actions" class="apply-bulk-actions-auto" type="submit">@T("Apply")</button>
    </fieldset>

    <fieldset class="search-actions">
        <input type="text" id="searchText" class="text-box single-line" name="@Html.NameOf(m => m.Options.SearchText)" value="@Model.Options.SearchText" />

        <button type="submit">@T("Search")</button>
    </fieldset>

    if (Model.Extensions.Count() > 0) {
        <ul class="contentItems theme">
        @foreach (var item in Model.Extensions) {
            <li>
                @{
            string extensionClass = "iconThumbnail";
            string iconUrl = @item.IconUrl;
            if (!string.IsNullOrWhiteSpace(@item.FirstScreenshot)) {
                iconUrl = @item.FirstScreenshot;
                extensionClass = "screenshotThumbnail";
            } else if (string.IsNullOrWhiteSpace(iconUrl)) {
                iconUrl = Href("../../Content/Images/imagePlaceholder.png");
                extensionClass = "screenshotThumbnail";
            }
                }

                <div class="summary">
                 @if (item.Notifications != null && item.Notifications.Count > 0) {
                                <div class="notifications">
                                @foreach (string notification in item.Notifications) {
                                    <h5>@Html.Raw(notification)</h5>
                                }
                                </div>
                            }
                </div>
                <div class="@extensionClass">
                    <div class="extensionDetails column">
                    <div class="extensionName @if (item.Installed) {<text>installed</text>}">
                            @if (!string.IsNullOrWhiteSpace(item.GalleryDetailsUrl)) {
                                <a href="@item.GalleryDetailsUrl">
                                    <h2>@item.Title<span> - @T("Version: {0}", item.Version)</span></h2>
                                </a>
                            } else {
                                <h2>@item.Title<span> - @T("Version: {0}", item.Version)</span></h2>
                            }
                        </div>

                        <div class="related">
                            @Html.ActionLink(T("Install").ToString(), "InstallGallery", "PackagingServices", new RouteValueDictionary { { "packageId", item.PackageId }, { "version", item.Version }, { "sourceId", item.Source.Id }, { "redirectUrl", HttpContext.Current.Request.RawUrl } }, null)@T(" | ")
                            <a href="@item.PackageStreamUri">@T("Download")</a>
                        </div>

                        <div class="properties">
                            <p>@(item.Description == null ? T("(No description").Text : item.Description)</p>
                            <ul class="pageStatus group">
                                <li>@T("Last Updated: {0}", item.LastUpdated)</li>
                                <li>&nbsp;&#124;&nbsp;@T("Author: {0}", !string.IsNullOrEmpty(item.Authors) ? item.Authors : T("Unknown").ToString())</li>
                                <li>&nbsp;&#124;&nbsp;@T("Downloads: {0}", item.DownloadCount)</li>
                                <li>&nbsp;&#124;&nbsp;@T("Website: ")
                                    @if (!string.IsNullOrEmpty(item.ProjectUrl)) { <a href="@item.ProjectUrl">@item.ProjectUrl</a> } else { @T("Unknown").ToString() }
                                </li>
                                <li class="rating">&nbsp;&#124;&nbsp;@T("Rating: ")
                                        <div class="ratings" style="width:@(15 * 5)px" title="@T("Rating: {0} out of 5 ({1} total).", item.Rating, item.RatingsCount)">
                                            <div class="score" style="width:@(15 * (item.Rating))px">&nbsp;</div>
                                        </div>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class="extensionThumbnail column">
                        <img src="@iconUrl" class="thumbnail" alt="theme" />
                    </div>
                </div>
            </li>}
        </ul>
    } else {
        <p>@T("No themes available.").ToString()</p>
    }

    @Display(Model.Pager)
}